### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by ASIMKHAN222** [capntrips/VbmetaPatcher#1]
how to install it? it does not installing in device
said
"there was a problem parsing the package"

**Comment by capntrips** [comment]
A quick Google search seems to indicate you have to enable installation from unknown sources.

Note that this app has little practical application, at this point. It was developed when Magisk didn't support installation without modification of the `vbmeta` partition.

If you have additional questions, I suggest posting them in the XDA thread:

https://forum.xda-developers.com/t/dev-eol-vbmeta-patcher-devinfo-patcher-and-boot-image-tool.4360405/
